name: Trivials
version: '1.0.0'
folia-supported: true
main: top.alwaysready.trivials.Trivials
api-version: '1.21'
authors: [ AlwaysReadyWby ]
description: 一些随机的小功能
commands:
  trivialreload:
  trivialdebug:
